In [21]:
hr=float(input("Enter Hours:"))
rt=float(input("Enter a rate:"))
if hr>40:
    py=40*rt+(hr-40)*1.5*rt
else:
    py=hr*rt
print("pay",py)

Enter Hours:45
Enter a rate:10
pay 475.0


In [18]:
x=5
if x==5:
    print("x equal to 5")
if x<=5:
    print("x is less than or equal to 5")
if x<6:
    print("x is less than 6")
if x!=6:
    print("x is not equal to 6")
if x>4:
    print("x is greater than 4")
if x>=5:
    print("x is greater than or equal to 5")

x equal to 5
x is less than or equal to 5
x is less than 6
x is not equal to 6
x is greater than 4
x is greater than or equal to 5


In [6]:
x=1
if x<2:
    print("Below 2")
elif x>=2:
    print("two or more")
else:
    print("something else")
    

Below 2


In [9]:
astr='Hello Bob'
try:
    istr=int(astr)
except:
    istr=-1
print("First",istr)
astr='123'
try:
    istr=int(astr)
except:
    istr=-1
print('Second',istr)

First -1
Second 123


In [10]:
astr='Bob'
try:
    print("Hello")
    istr=int(astr)
    print("There")
except:
    istr=-1
print("Done",istr)

Hello
Done -1


In [31]:
rawstr=input("Enter a number")
try:
    ival=int(rawstr)
except:
    ival=-1
if ival>0:
    print("Nice work")
else:
    print("Not a number")

Enter a number4
Nice work


In [34]:
hr=float(input("Enter a hour:"))
rt=float(input("Enter a rate:"))
def compute(a,b):
    if a>40:
        return 40*b+(a-40)*1.5*b
    else:
        return a*b
print("pay:",compute(hr,rt))
    

Enter a hour:45
Enter a rate:10
pay: 475.0


In [24]:
while True:
    line=input('> ')
    if line=='done':
        break
    print(line)
print('Done!')

> hi
hi
> hello
hello
> done
Done!


In [26]:
while True:
    line=input('> ')
    if line[0]=='#':
        continue
    if line=='done':
        break
    print(line)
print('Done!')

> hi
hi
> hello
hello
> #good
> #fine
> done
Done!


In [28]:
friends=['Joseph','Glenn','Sally',7,8]
for friend in friends:
    print("Happy New year",friend)
print("Done!")

Happy New year Joseph
Happy New year Glenn
Happy New year Sally
Happy New year 7
Happy New year 8
Done!


In [33]:
large=-1
print("Before",large)
for thing in [9,41,12,3,74,15]:
    if thing>large:
        large=thing
print("After",large)

Before -1
After 74


In [35]:
Sum=0
count=0
for thing in [9,41,12,3,74,15]:
    Sum=Sum+thing
    count+=1
avg=Sum/count
print("Average:",avg)

Average: 25.666666666666668


In [37]:
found=False
print("Before",found)
for value in [9,41,12,3,74,15]:
    if value==3:
        found=True
    print(found,value)
print("After",found)

Before False
False 9
False 41
False 12
True 3
True 74
True 15
After True


In [41]:
smallest =2
print("Before")
for value in [3,41,12,9,74,15]:
    if smallest is None:
        smallest=value
    elif value<smallest:
        smallest=value
    print(smallest,value)
print("After",smallest)

Before
2 3
2 41
2 12
2 9
2 74
2 15
After 2


In [42]:
first='this is arun'.split(' ')[0]
print(first)

this


In [43]:
sales_record={'price':3.24,'num_items':4,'person':'Arockyaraj'}
sales_statement='{} bought {} item(s) at a price of INR {} each for a total of {}'
print(sales_statement.format(sales_record['person'],sales_record['num_items'],sales_record['price'],sales_record['num_items']*sales_record['price']))

Arockyaraj bought 4 item(s) at a price of INR 3.24 each for a total of 12.96


In [47]:
import datetime as dt
import time as tm
tm.time()


1565796232.5352838

In [48]:
from datetime import date
from datetime import time
from datetime import datetime
today=date.today()
print(today)

2019-08-14


In [49]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 8, 14, 20, 57, 41, 342568)

In [53]:
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2019, 8, 14, 20, 57, 41)

In [59]:
delta=dt.timedelta(days=100)
delta

datetime.timedelta(100)

In [62]:
class Person:
    institute='Manipal School of Information Sciences'
    def set_name(self,new_name):
        self.name=new_name
    def set_location(self,new_location):
        self.location=new_location
person=Person()
person.set_name('Arockiaraj')
person.set_location("Manipal, Udupi, Karnataka")
print('{} lives in {} and works in the institute {}'.format(person.name,person.location,person.institute))

Arockiaraj lives in Manipal, Udupi, Karnataka and works in the institute Manipal School of Information Sciences


In [1]:
store1=[10.00,11.00,12.24,2.34]
store2=[9.00,11.10,12.34,2.01]
cheapest=map(min,store1,store2)
list(cheapest)

[9.0, 11.0, 12.24, 2.01]

In [71]:
for items in cheapest:
    print(items)


9.0
11.0
12.24
2.01


In [74]:
my_function=lambda a,b,c : a+b
my_function(5,2,9)

7

In [76]:
people=['Dr. Christopher Brooks','Dr. Kevyn Collins-Thompson','Dr. VG Vinod vydiswaran','Dr. VP Bhat']
def split_title_and_name(person):
    return person.split()[0]+' '+person.split()[-1]

In [77]:
for person in people:
    print(split_title_and_name(person)==(lambda x:x.split()[0]+' '+x.split()[-1])(person))

True
True
True
True


In [78]:
list(map(split_title_and_name,people))==list(map(lambda person:person.split()[0]+' '+person.split()[-1],people))

True

In [13]:
def calculatesquare(n):
    return n*n
numbers=(1,2,3,4)
result=map(calculatesquare,numbers)
print(list(result))


[1, 4, 9, 16]


In [12]:
for item in list(result):
    print(item)

In [19]:
numbers=(1,2,3,4)
result=map(lambda x:x*x,numbers)
print(result)
list(result)
even=lambda x:x%2==0
even(2)

True

In [18]:
num1=[4,5,6]
num2=[5,6,7]
result=map(lambda x,y:x+y,num1,num2)
list(result)

[9, 11, 13]

In [20]:
people=['Dr. Christopher Brooks','Dr. Kevyn Collins-Thompson','Dr. VG Vinod vydiswaran','Dr. VP Bhat']

In [38]:
def split_title_and_name(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '%s %s'%(title,lastname)

In [39]:
list(map(split_title_and_name,people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. vydiswaran', 'Dr. Bhat']

In [37]:
a=3
b=3
print("a=%d b=%d"%(a,b))

a=3 b=3


In [40]:
z=lambda x,y:x*y
z(3,4)


12

In [43]:
my_list=[1,5,4,6,8,11,3,12]
new_list=map(lambda x:x*2,my_list)
print(list(new_list))

[2, 10, 8, 12, 16, 22, 6, 24]


In [44]:
my_function=lambda a,b:a+b
my_function(10,2)

12

In [49]:
people=['Dr. Christopher Brooks','Dr. Kevyn Collins-Thompson','Dr. VG Vinod vydiswaran','Dr. VP Bhat']
def split_title_and_name(person):
    return person.split()[0]+' '+person.split()[-1]

In [54]:
for person in people:
    print(split_title_and_name(person)==(lambda x:x.split()[0]+' '+x.split()[-1])(person))
    print("function result:",split_title_and_name(person))
    print("lambda result:",(lambda x:x.split()[0]+' '+x.split()[-1])(person))

True
function result: Dr. Brooks
lambda result: Dr. Brooks
True
function result: Dr. Collins-Thompson
lambda result: Dr. Collins-Thompson
True
function result: Dr. vydiswaran
lambda result: Dr. vydiswaran
True
function result: Dr. Bhat
lambda result: Dr. Bhat


In [55]:
my_list=[]
for number in range(0,20):
    if number%2==0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [57]:
my_list=[number for number in range(0,20) if number%2==0]
my_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [63]:
def times_tables():
    lst=[]
    for i in range(10):
        for j in range(10):
            lst.append(i*j)
    return lst
print(times_tables())
times_tables()==[j*i for i in range(10) for j in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


True

In [69]:
import numpy as np
l=np.array([4,5,6])
l

array([4, 5, 6])

In [66]:
l=[4,5,6,7]
print(np.mean(l))

5.5


In [72]:
n=np.arange(10)
print(n)
n.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
lspace=np.linspace(0,4,9)
lspace

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [74]:
lspace.resize(3,3)
lspace

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [75]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [76]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [77]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [78]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [79]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [81]:
num=np.matrix([[11,121,130],[613,34,13],[514,50,16]])
print("Main diagonal:\n",np.diag(num))
print("Elements above Main diagonal:\n",np.diag(num,1))
print("Elements below Main diagonal:\n",np.diag(num,-1))


Main diagonal:
 [11 34 16]
Elements above Main diagonal:
 [121  13]
Elements below Main diagonal:
 [613  50]


In [82]:
np.array([2,3,4]*3)

array([2, 3, 4, 2, 3, 4, 2, 3, 4])

In [83]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [85]:
p=np.ones((3,3),int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [86]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [87]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [88]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [89]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [92]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/2)
print(x**2)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[ 0.5  1.   1.5]
[1 4 9]


In [91]:
a=[3,4,5,8]
b=[4.5,7,8]
print(a+b)

[3, 4, 5, 8, 4.5, 7, 8]


In [93]:
x.dot(y)

32

In [94]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [96]:
print(len(z))
z.size

2


6

In [97]:
z.shape

(2, 3)

In [98]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [99]:
z.dtype

dtype('int64')

In [100]:
z=z.astype('f')
z.dtype

dtype('float32')

In [101]:
a=np.array([-4,-2,1,3,5])
a.sum()

3

In [102]:
a.max()

5

In [103]:
a.min()

-4

In [104]:
a.mean()

0.59999999999999998

In [105]:
a.std()

3.2619012860600183

In [106]:
a.argmax()#location of maximum

4

In [108]:
a.argmin()#location of minimum

0

In [109]:
s=np.arange(6)
s

array([0, 1, 2, 3, 4, 5])

In [111]:
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [112]:
s[0],s[4],s[-1]

(0, 16, 25)

In [113]:
s[1:5]

array([ 1,  4,  9, 16])

In [114]:
s[-4:]

array([ 4,  9, 16, 25])

In [115]:
s[::-1]

array([25, 16,  9,  4,  1,  0])

In [116]:
s[-5:-2]

array([1, 4, 9])

In [127]:
r=np.arange(100)
r.resize((10,10))
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
print("diagonal:",np.diag(r))
print("above diagonal",np.diag(r,1))
print("below diagonal",np.diag(r,-1))

diagonal: [ 0 11 22 33 44 55 66 77 88 99]
above diagonal [ 1 12 23 34 45 56 67 78 89]
below diagonal [10 21 32 43 54 65 76 87 98]


In [121]:
r[2,2]

22

In [122]:
r[3,3:6]

array([33, 34, 35])

In [124]:
r[:2,:-1]# we are selecting all row upto 2(exclude ),and all column except last column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [128]:
r[-1,::3]
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [131]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [132]:
r2[:]=0 #r is also will change
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [133]:
r


array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [134]:
#to avoid this,make a copy
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [136]:
r_copy[:]=10
print(r_copy,'\n')
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]
