In [2]:
import  numpy as np
old=np.array([[1,1,1],[1,1,1]])
new=old
new[0,:2]=0
print(new)

[[0 0 1]
 [1 1 1]]


array([[0, 0, 1],
       [1, 1, 1]])

In [11]:
new=np.array([[1,1,1],[1,1,1],[1,1,1]])
new[1,1]=0
new

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [23]:
new=np.ones([10,10])
print(new)
new[:2,:]=0
new

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [21]:
import pandas as pd
pd.Series?

In [24]:
animals=['Tigers','Bear','Moose']
pd.Series(animals)

0    Tigers
1      Bear
2     Moose
dtype: object

In [27]:
numbers=[1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [28]:
np.nan==None

False

In [29]:
np.nan==np.nan

False

In [30]:
np.isnan(np.nan)

True

In [32]:
sports={"archary":"Butan","Golf":"scotland","sumo":"japan"}
s=pd.Series(sports)
s

Golf       scotland
archary       Butan
sumo          japan
dtype: object

In [33]:
s.index

Index(['Golf', 'archary', 'sumo'], dtype='object')

In [34]:
s.values

array(['scotland', 'Butan', 'japan'], dtype=object)

In [38]:
sports.keys()
sports.values()

dict_values(['Butan', 'scotland', 'japan'])

In [43]:
print(s)
s.iloc[2]
s.loc["Golf"]

Golf       scotland
archary       Butan
sumo          japan
dtype: object


'scotland'

In [44]:
s['Golf']

'scotland'

In [51]:
sports={99:"Bhutan",100:"scotland",80:"japan"}
sports[99]

'Bhutan'

In [52]:
s=pd.Series(sports)

In [56]:
s.iloc[0]

'japan'

In [50]:
s.loc[99]

'Bhutan'

In [54]:
s.iloc[99]

IndexError: single positional indexer is out-of-bounds

In [57]:
s=pd.Series([100.00,120.00,101.00,3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

In [58]:
total=0
for item in s:
    total+=item
print(total)

324.0


In [59]:
total=np.sum(s)
print(total)

324.0


In [63]:
tot=np.arange(5)
tot.sum()

10

In [65]:
s=pd.Series(np.random.randint(0,10,7))
s.head()

0    6
1    5
2    6
3    6
4    2
dtype: int64

In [66]:
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    718
1    228
2    757
3    385
4    556
dtype: int64

In [67]:
len(s)

10000

In [74]:
%%timeit -n 100
summ=0
for item in s:
    summ+=item

800 µs ± 24.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [71]:
%%timeit -n 100
summ=np.sum(s)

39.4 µs ± 3.88 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
s+=2 #adds two to each item in s using broadcasting
s.head()

0    720
1    230
2    759
3    387
4    558
dtype: int64

In [75]:
s=pd.Series([1,2,3])
s.loc['Animal']='Bears'
s

0             1
1             2
2             3
Animal    Bears
dtype: object

In [81]:
original_sports=pd.Series({"Archary":"Bhutan","Golf":"Scotland","Sumo":"Japan","Taekwondo":"south korea"})
cricket_loving_countries=pd.Series(['Australia','India','Pakistan','England'],index=['Cricket']*4)
all_countries=original_sports.append(cricket_loving_countries)

In [79]:
all_countries

Archary           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    south korea
Cricket        Australia
Cricket            India
Cricket         Pakistan
Cricket          England
dtype: object

In [82]:
all_countries.loc['Cricket']

Cricket    Australia
Cricket        India
Cricket     Pakistan
Cricket      England
dtype: object

In [89]:
purchase_1=pd.Series({'Name':'Chris',"Item Purchased":"Dog Food","Cost":5.00})
purchase_2=pd.Series({'Name':'Kevin',"Item Purchased":"Kitty Litter","Cost":2.50})
purchase_3=pd.Series({'Name':"Vinod","Item Purchased":"Bird Seed","Cost":5.00})
df=pd.DataFrame([purchase_1,purchase_2,purchase_3],index=['Store 1','Store 1','Store 2'])
df.head()


Cost Item Purchased   Name
Store 1   5.0       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevin
Store 2   5.0      Bird Seed  Vinod

In [90]:
df.loc['Store 2']

Cost                      5
Item Purchased    Bird Seed
Name                  Vinod
Name: Store 2, dtype: object

In [91]:
df.loc['Store 1']

Cost Item Purchased   Name
Store 1   5.0       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevin

In [92]:
df.loc['Store 1','Cost']

Store 1    5.0
Store 1    2.5
Name: Cost, dtype: float64

In [93]:
df.T

Store 1       Store 1    Store 2
Cost                   5           2.5          5
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Name               Chris         Kevin      Vinod

In [96]:
df.T.loc['Cost']

Store 1      5
Store 1    2.5
Store 2      5
Name: Cost, dtype: object

In [97]:
df.loc[:,['Name','Cost']]


Name  Cost
Store 1  Chris   5.0
Store 1  Kevin   2.5
Store 2  Vinod   5.0

In [98]:
df.drop('Store 1')

Cost Item Purchased   Name
Store 2   5.0      Bird Seed  Vinod

In [99]:
df

Cost Item Purchased   Name
Store 1   5.0       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevin
Store 2   5.0      Bird Seed  Vinod

In [100]:
copy_df=df.copy()
copy_df=copy_df.drop("Store 1")
copy_df

Cost Item Purchased   Name
Store 2   5.0      Bird Seed  Vinod

In [101]:
copy_df.drop?

In [102]:
del copy_df['Name']
copy_df

Cost Item Purchased
Store 2   5.0      Bird Seed

In [103]:
df['Location']=None
df

Cost Item Purchased   Name Location
Store 1   5.0       Dog Food  Chris     None
Store 1   2.5   Kitty Litter  Kevin     None
Store 2   5.0      Bird Seed  Vinod     None

In [110]:
costs=df['Cost']
costs

Store 1    5.0
Store 1    2.5
Store 2    5.0
Name: Cost, dtype: float64

In [111]:
costs+=2
costs

Store 1    7.0
Store 1    4.5
Store 2    7.0
Name: Cost, dtype: float64