In [5]:
import time as tm
import datetime as dt
tm.time()

1568393546.8808594

In [7]:
dt.date.today()

datetime.date(2019, 9, 13)

In [11]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 13, 22, 24, 43, 208984)

In [12]:
dtnow.year

2019

In [13]:
dtnow.month

9

In [20]:
g=dt.timedelta(days=167)

In [22]:
g.days

167

In [25]:
s1=[3,45,33,3,4,55]
s2=[5,66,44,5,3,2,2]
g=list(map(max,s1,s2))

In [26]:
g

[5, 66, 44, 5, 4, 55]

In [27]:
k=lambda x:x**2
k(9)

81

In [35]:
class People:
    inst="manipal school"
    def set_name(self,new_name):
        self.name=new_name
    def new_location(self,loc):
        self.loc=loc
p=People()
p.set_name("kavya")
p.new_location("thumakur")
print("{} is in {} at {}".format(p.name,p.loc,p.inst))

kavya is in thumakur at manipal school


In [58]:
k= lambda x:x%2==0
x=list(k(g) for g in range(9) )
x

[True, False, True, False, True, False, True, False, True]

In [68]:
def square(n):
    return n**2
l=[7]
k=map(square,(l))
list(k)

[49]

In [3]:
k=["Arun c kumar","Ravindra b nayak","manvith k nayak"]

In [4]:
for i in k:
    print(i.split()[0])
    print(i.split()[-1])

Arun
kumar
Ravindra
nayak
manvith
nayak


In [5]:
def split_name(p):
    first=p.split()[0]
    last=p.split()[-1]
    return '{} {}'.format(first,last)


In [6]:
list(map(split_name,k))

['Arun kumar', 'Ravindra nayak', 'manvith nayak']

In [81]:
k=list( k for k in range(20) if k%2==0)
k

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [84]:
import numpy as np
import pandas as pd
k=np.array([2,3,4,5,6])
k

array([2, 3, 4, 5, 6])

In [88]:
k.mean()

4.0

In [89]:
k.std()

1.4142135623730951

In [92]:
np.dtype?

In [93]:
k.dtype

dtype('int32')

In [94]:
k.ndim

1

In [95]:
k.size

5

In [96]:
len(k)

5

In [97]:
k

array([2, 3, 4, 5, 6])

In [100]:
k=np.linspace(1,9,10)

In [101]:
k

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [102]:
k.reshape(2,5)

array([[1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556],
       [5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ]])

In [103]:
k.resize(2,5)

In [104]:
k

array([[1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556],
       [5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ]])

In [105]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [113]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [112]:
np.ones?

In [115]:
a=np.random.randint(1,10,(3,3))

In [116]:
a

array([[7, 6, 4],
       [3, 9, 4],
       [9, 4, 9]])

In [117]:
b=np.matrix(a)

In [118]:
b

matrix([[7, 6, 4],
        [3, 9, 4],
        [9, 4, 9]])

In [119]:
np.diag(b)

array([7, 9, 9])

In [120]:
np.diag(b,1)

array([6, 4])

In [121]:
np.diag(b,-1)

array([3, 4])

In [124]:
np.array([2,3,4]*2)

array([2, 3, 4, 2, 3, 4])

In [125]:
np.repeat([5,7,8],4)

array([5, 5, 5, 5, 7, 7, 7, 7, 8, 8, 8, 8])

In [126]:
p=np.ones((3,3),int)

In [129]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [130]:
p.dtype

dtype('int32')

In [131]:
p=p.astype('f')

In [132]:
p.dtype

dtype('float32')

In [136]:
p=np.array(["23","567"])
p.dtype

dtype('<U3')

In [142]:
p=p.astype(int)

In [143]:
p.dtype

dtype('int32')

In [144]:
r=np.random.randint(0,10,(10,10))

In [145]:
r

array([[1, 2, 8, 1, 8, 5, 0, 8, 2, 6],
       [2, 5, 3, 0, 2, 2, 8, 6, 5, 6],
       [3, 3, 7, 7, 3, 9, 7, 9, 9, 9],
       [9, 7, 6, 9, 8, 4, 2, 9, 6, 1],
       [0, 2, 3, 5, 2, 2, 0, 2, 4, 7],
       [9, 7, 0, 9, 5, 0, 1, 8, 9, 2],
       [8, 7, 0, 9, 6, 5, 7, 8, 8, 0],
       [4, 2, 7, 3, 9, 8, 3, 7, 9, 7],
       [3, 3, 2, 6, 4, 1, 8, 8, 0, 2],
       [0, 5, 4, 4, 0, 2, 9, 7, 4, 3]])

In [146]:
r[:,6:8]=0

In [154]:
r.T

array([[1, 2, 3, 9, 0, 9, 8, 4, 3, 0],
       [2, 5, 3, 7, 2, 7, 7, 2, 3, 5],
       [8, 3, 7, 6, 3, 0, 0, 7, 2, 4],
       [1, 0, 7, 9, 5, 9, 9, 3, 6, 4],
       [8, 2, 3, 8, 2, 5, 6, 9, 4, 0],
       [5, 2, 9, 4, 2, 0, 5, 8, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 5, 9, 6, 4, 9, 8, 9, 0, 4],
       [6, 6, 9, 1, 7, 2, 0, 7, 2, 3]])

In [1]:
import numpy as np


In [3]:
np.random.randint(10,20,(3,4))

array([[12, 14, 10, 13],
       [14, 10, 10, 16],
       [18, 13, 18, 12]])

In [6]:
np.random.random(30).mean()

0.49200673532639205

In [10]:
a=9

In [27]:
k=np.array([7])

In [28]:
k.dtype

dtype('int32')

In [29]:
k=k.astype(str)

In [30]:
k.dtype

dtype('<U11')

In [31]:
k=np.array('7')

In [32]:
k.dtype

dtype('<U1')

In [33]:
k=np.array([1,2,0,0,4,0])

In [39]:
np.where(k!=0)

(array([0, 1, 4], dtype=int64),)

In [40]:
k=np.random.random(30)

In [41]:
k.mean()

0.44362118018067176

In [42]:
k=np.random.random(10)

In [43]:
k[k==k.max()]=0

In [44]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [1]:
import time as tm
import datetime as dt


In [2]:
tm.time()

1574469943.6835938

In [5]:
from datetime import date
date.today()

datetime.date(2019, 11, 23)

In [7]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 11, 23, 6, 17, 27, 731445)

In [17]:
dt.timedelta(days=100)

datetime.timedelta(days=100)

In [12]:
delta

datetime.timedelta(days=100)

In [13]:
dtnow

datetime.datetime(2019, 11, 23, 6, 17, 27, 731445)